#ifndef __xmi_config_h__
#define __xmi_config_h__


#warning "xmi_config.h should be generated by configure"
#define PLATFORM dummy

#ifndef PLATFORM
#error "PLATFORM is not defined"
#endif

#if PLATFORM == dummy
#define XMI_PROTOCOL_NQUADS	48
#define XMI_REQUEST_NQUADS	32
typedef struct XMIQuad
{
    unsigned w0; /**< Word[0] */
    unsigned w1; /**< Word[1] */
    unsigned w2; /**< Word[2] */
    unsigned w3; /**< Word[3] */
}
XMIQuad __attribute__ ((__aligned__ (16)));
typedef XMIQuad XMI_CollectiveProtocol_t [32*2];   /**< Opaque datatype for collective protocols */
typedef XMIQuad XMI_CollectiveRequest_t  [32*8*4]; /**< Opaque datatype for collective requests */
#endif

#if PLATFORM == sockets

#endif

#if PLATFORM == bgp

#endif

#if PLATFORM == bgq

#endif

#if PLATFORM == lapiunix

#endif

#if PLATFORM == mpi

#endif


#endif /* __xmi_config_h__ */
